// <auto-generated />
namespace MVCSBD_Sklep.Migrations.XmoreltronikEntities
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OrderCount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderCount));
        
        string IMigrationMetadata.Id
        {
            get { return "202112032009594_OrderCount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
